// Real LULC classification systems from authoritative sources
const PRESETS = {

  binary: {
    name: 'Binary (Positive / Negative)',
    description: 'Simple two-class validation schema',
    source: 'Custom',
    classes: [
      { code: 1, label: 'Positive', color: '#22c55e', key: '1', seasonalPattern: '' },
      { code: 2, label: 'Negative', color: '#ef4444', key: '2', seasonalPattern: '' },
    ],
  },

  // NDVI ranges below are suggested seed values from typical Sentinel-2 NDVI
  // statistics for each class. Users can edit them per-project in the NDVI
  // panel — the band updates the project's classSchema, not this file.

  molca: {
    name: 'MOLCA 2019 (10 classes)',
    description: 'Morocco Land Cover Assessment used for Planet/Sentinel validation studies',
    source: 'MOLCA 2019',
    classes: [
      { code: 20, label: 'Forest',                  color: '#548235', key: '1', ndviRange: [0.3, 0.9],   seasonalPattern: 'High flat or seasonal dip' },
      { code: 5,  label: 'Shrubland',               color: '#c6e0b4', key: '2', ndviRange: [0.2, 0.5],   seasonalPattern: 'Flat, minor seasonal variation' },
      { code: 7,  label: 'Grassland',               color: '#66ff33', key: '3', ndviRange: [0.2, 0.6],   seasonalPattern: 'Gradual rise, one broad peak' },
      { code: 8,  label: 'Cropland',                color: '#ffc000', key: '4', ndviRange: [0.2, 0.6],   seasonalPattern: 'Sharp spike then sharp drop' },
      { code: 9,  label: 'Wetland',                 color: '#9bc2e6', key: '5', ndviRange: [0.2, 0.5],   seasonalPattern: 'Moderate, may spike with flooding' },
      { code: 10, label: 'Lichens and Mosses',      color: '#ededed', key: '6', ndviRange: [0.1, 0.2],   seasonalPattern: 'Stable, flat line' },
      { code: 12, label: 'Bareland',                color: '#bf8f00', key: '7', ndviRange: [0.0, 0.1],   seasonalPattern: 'Stable, flat near zero' },
      { code: 13, label: 'Built-up',                color: '#ff0000', key: '8', ndviRange: [0.0, 0.1],   seasonalPattern: 'Stable, flat near zero' },
      { code: 15, label: 'Water',                   color: '#1f4e78', key: '9', ndviRange: [-0.3, 0.0],  seasonalPattern: 'Stable, flat, negative values' },
      { code: 16, label: 'Permanent Ice and Snow',  color: '#e8e8ff', key: '0', ndviRange: [-0.2, 0.1],  seasonalPattern: 'Stable, flat near zero' },
    ],
  },

  corine_l1: {
    name: 'CORINE Land Cover Level 1 (5 classes)',
    description: 'EEA CORINE Land Cover — Level 1 aggregation. Europe-wide, 100m resolution.',
    source: 'EEA CORINE 2018',
    url: 'https://land.copernicus.eu/pan-european/corine-land-cover',
    classes: [
      { code: 1, label: 'Artificial Surfaces',            color: '#e6004d', key: '1', ndviRange: [0.0, 0.1],   seasonalPattern: 'Stable, flat near zero' },
      { code: 2, label: 'Agricultural Areas',             color: '#ffffa8', key: '2', ndviRange: [0.2, 0.7],   seasonalPattern: 'Sharp spike then sharp drop' },
      { code: 3, label: 'Forest & Semi-natural Areas',    color: '#80ff00', key: '3', ndviRange: [0.3, 0.9],   seasonalPattern: 'High flat or seasonal dip' },
      { code: 4, label: 'Wetlands',                       color: '#4dbed2', key: '4', ndviRange: [0.2, 0.5],   seasonalPattern: 'Moderate, may spike with flooding' },
      { code: 5, label: 'Water Bodies',                   color: '#0064ff', key: '5', ndviRange: [-0.3, 0.0],  seasonalPattern: 'Stable, flat, negative values' },
    ],
  },

  corine_l2: {
    name: 'CORINE Land Cover Level 2 (15 classes)',
    description: 'EEA CORINE Land Cover — Level 2 aggregation. Europe-wide, 100m resolution.',
    source: 'EEA CORINE 2018',
    url: 'https://land.copernicus.eu/pan-european/corine-land-cover',
    classes: [
      { code: 11, label: 'Urban Fabric',                            color: '#e6004d', key: '1', ndviRange: [0.0, 0.2],   seasonalPattern: 'Low, slight summer green bump' },
      { code: 12, label: 'Industrial / Commercial Units',           color: '#cc4df2', key: '2', ndviRange: [0.0, 0.1],   seasonalPattern: 'Stable, flat near zero' },
      { code: 13, label: 'Mine / Dump / Construction',              color: '#cc0000', key: '3', ndviRange: [0.0, 0.2],   seasonalPattern: 'Flat, irregular bare signal' },
      { code: 14, label: 'Artificial Non-agricultural Vegetated',   color: '#e6cccc', key: '4', ndviRange: [0.2, 0.6],   seasonalPattern: 'Mild seasonal green rise' },
      { code: 21, label: 'Arable Land',                            color: '#ffffa8', key: '5', ndviRange: [0.2, 0.8],    seasonalPattern: 'Sharp spike then sharp drop' },
      { code: 22, label: 'Permanent Crops',                        color: '#e6e600', key: '6', ndviRange: [0.3, 0.7],    seasonalPattern: 'Broad plateau, gentle dip' },
      { code: 23, label: 'Pastures',                               color: '#e8beff', key: '7', ndviRange: [0.3, 0.7],    seasonalPattern: 'Gradual rise, one broad peak' },
      { code: 24, label: 'Heterogeneous Agricultural Areas',       color: '#e68000', key: '8', ndviRange: [0.2, 0.7],    seasonalPattern: 'Mixed peaks, multi-modal' },
      { code: 31, label: 'Forests',                                color: '#80ff00', key: '9', ndviRange: [0.3, 0.9],    seasonalPattern: 'High flat or seasonal dip' },
      { code: 32, label: 'Shrub / Herbaceous Vegetation',          color: '#ccf24d', key: '0', ndviRange: [0.2, 0.6],    seasonalPattern: 'Flat, minor seasonal variation' },
      { code: 33, label: 'Open Spaces (sparse vegetation)',        color: '#a6f200', key: 'q', ndviRange: [0.0, 0.3],    seasonalPattern: 'Low, weak summer bump' },
      { code: 41, label: 'Inland Wetlands',                        color: '#00a6e6', key: 'w', ndviRange: [0.2, 0.5],    seasonalPattern: 'Moderate, may spike with flooding' },
      { code: 42, label: 'Coastal Wetlands',                       color: '#00ccf2', key: 'e', ndviRange: [0.1, 0.5],    seasonalPattern: 'Tidal noise, moderate summer rise' },
      { code: 51, label: 'Inland Waters',                          color: '#80f2e6', key: 'r', ndviRange: [-0.3, 0.0],   seasonalPattern: 'Stable, flat, negative values' },
      { code: 52, label: 'Marine Waters',                          color: '#0064ff', key: 't', ndviRange: [-0.3, 0.0],   seasonalPattern: 'Stable, flat, negative values' },
    ],
  },

  igbp: {
    name: 'IGBP / MODIS MCD12Q1 (17 classes)',
    description: 'International Geosphere-Biosphere Programme scheme. Used in NASA MODIS MCD12Q1 Land Cover Type 1 product at 500m global resolution.',
    source: 'NASA MODIS MCD12Q1 v6.1',
    url: 'https://lpdaac.usgs.gov/products/mcd12q1v006/',
    classes: [
      { code: 1,  label: 'Evergreen Needleleaf Forests',           color: '#1c5f2c', key: '1', ndviRange: [0.4, 0.8],   seasonalPattern: 'Consistently high, almost flat' },
      { code: 2,  label: 'Evergreen Broadleaf Forests',            color: '#1c7a29', key: '2', ndviRange: [0.6, 0.9],   seasonalPattern: 'Very high, nearly flat year-round' },
      { code: 3,  label: 'Deciduous Needleleaf Forests',           color: '#87982f', key: '3', ndviRange: [0.1, 0.8],   seasonalPattern: 'Drops in dormant season, recovers' },
      { code: 4,  label: 'Deciduous Broadleaf Forests',            color: '#86c15c', key: '4', ndviRange: [0.2, 0.9],   seasonalPattern: 'Drops in dormant season, recovers' },
      { code: 5,  label: 'Mixed Forests',                          color: '#4ea040', key: '5', ndviRange: [0.3, 0.9],   seasonalPattern: 'High with moderate seasonal dip' },
      { code: 6,  label: 'Closed Shrublands',                      color: '#dbba50', key: '6', ndviRange: [0.2, 0.6],   seasonalPattern: 'Flat, mild seasonal rise' },
      { code: 7,  label: 'Open Shrublands',                        color: '#d48b31', key: '7', ndviRange: [0.1, 0.4],   seasonalPattern: 'Low, weak seasonal variation' },
      { code: 8,  label: 'Woody Savannas',                         color: '#dada8b', key: '8', ndviRange: [0.2, 0.7],   seasonalPattern: 'Broad wet-season peak' },
      { code: 9,  label: 'Savannas',                               color: '#e7e754', key: '9', ndviRange: [0.2, 0.6],   seasonalPattern: 'Single wet-season peak' },
      { code: 10, label: 'Grasslands',                             color: '#c5e755', key: '0', ndviRange: [0.2, 0.6],   seasonalPattern: 'Gradual rise, one broad peak' },
      { code: 11, label: 'Permanent Wetlands',                     color: '#6c9fb8', key: 'q', ndviRange: [0.2, 0.5],   seasonalPattern: 'Moderate, may spike with flooding' },
      { code: 12, label: 'Croplands',                              color: '#c24f44', key: 'w', ndviRange: [0.2, 0.8],   seasonalPattern: 'Sharp spike then sharp drop' },
      { code: 13, label: 'Urban and Built-up',                     color: '#a5114e', key: 'e', ndviRange: [0.0, 0.1],   seasonalPattern: 'Stable, flat near zero' },
      { code: 14, label: 'Cropland / Natural Vegetation Mosaics',  color: '#ff6d4c', key: 'r', ndviRange: [0.2, 0.7],   seasonalPattern: 'Mixed peaks, multi-modal' },
      { code: 15, label: 'Permanent Snow and Ice',                 color: '#c8c8dc', key: 't', ndviRange: [-0.2, 0.1],  seasonalPattern: 'Stable, flat near zero' },
      { code: 16, label: 'Barren',                                 color: '#f9f5d7', key: 'y', ndviRange: [0.0, 0.1],   seasonalPattern: 'Stable, flat near zero' },
      { code: 17, label: 'Water Bodies',                           color: '#1c22c4', key: 'u', ndviRange: [-0.3, 0.0],  seasonalPattern: 'Stable, flat, negative values' },
    ],
  },

  esa_cci: {
    name: 'ESA CCI Land Cover (22 classes)',
    description: 'ESA Climate Change Initiative Land Cover — global annual maps at 300m (1992–2020). Official LCCS-based colormap.',
    source: 'ESA CCI-LC v2.1.1',
    url: 'https://www.esa-landcover-cci.org/',
    classes: [
      { code: 10,  label: 'Cropland, rainfed',                        color: '#ffff64', key: '1', ndviRange: [0.2, 0.6],   seasonalPattern: 'Sharp spike then sharp drop' },
      { code: 20,  label: 'Cropland, irrigated',                      color: '#aaf0f0', key: '2', ndviRange: [0.3, 0.9],   seasonalPattern: 'High broad plateau, late drop' },
      { code: 30,  label: 'Mosaic cropland / natural veg.',           color: '#dcf064', key: '3', ndviRange: [0.2, 0.7],   seasonalPattern: 'Mixed peaks, multi-modal' },
      { code: 40,  label: 'Mosaic natural veg. / cropland',           color: '#c8c864', key: '4', ndviRange: [0.2, 0.7],   seasonalPattern: 'Broad peak, mild secondary bump' },
      { code: 50,  label: 'Tree cover, broadleaved, evergreen',       color: '#006400', key: '5', ndviRange: [0.6, 0.9],   seasonalPattern: 'Very high, nearly flat year-round' },
      { code: 60,  label: 'Tree cover, broadleaved, deciduous',       color: '#00a000', key: '6', ndviRange: [0.2, 0.9],   seasonalPattern: 'Drops in dormant season, recovers' },
      { code: 70,  label: 'Tree cover, needleleaved, evergreen',      color: '#003c00', key: '7', ndviRange: [0.4, 0.8],   seasonalPattern: 'Consistently high, almost flat' },
      { code: 80,  label: 'Tree cover, needleleaved, deciduous',      color: '#285000', key: '8', ndviRange: [0.1, 0.8],   seasonalPattern: 'Drops in dormant season, recovers' },
      { code: 90,  label: 'Tree cover, mixed leaf type',              color: '#788200', key: '9', ndviRange: [0.3, 0.9],   seasonalPattern: 'High with moderate seasonal dip' },
      { code: 100, label: 'Mosaic tree/shrub / herbaceous',           color: '#8ca000', key: '0', ndviRange: [0.2, 0.7],   seasonalPattern: 'Broad peak, mixed signals' },
      { code: 110, label: 'Mosaic herbaceous / tree/shrub',           color: '#be9600', key: 'q', ndviRange: [0.2, 0.6],   seasonalPattern: 'Gradual rise, one broad peak' },
      { code: 120, label: 'Shrubland',                                color: '#966400', key: 'w', ndviRange: [0.2, 0.5],   seasonalPattern: 'Flat, minor seasonal variation' },
      { code: 130, label: 'Grassland',                                color: '#ffb432', key: 'e', ndviRange: [0.2, 0.6],   seasonalPattern: 'Gradual rise, one broad peak' },
      { code: 140, label: 'Lichens and Mosses',                       color: '#ffdcd2', key: 'r', ndviRange: [0.1, 0.2],   seasonalPattern: 'Stable, flat line' },
      { code: 150, label: 'Sparse vegetation (<15%)',                 color: '#ffebaf', key: 't', ndviRange: [0.0, 0.2],   seasonalPattern: 'Low, weak summer bump' },
      { code: 160, label: 'Tree cover, flooded, freshwater',          color: '#00785a', key: 'y', ndviRange: [0.3, 0.8],   seasonalPattern: 'High, dips with flood pulse' },
      { code: 170, label: 'Tree cover, flooded, saline',              color: '#009678', key: 'u', ndviRange: [0.2, 0.7],   seasonalPattern: 'Moderate, tidal modulation' },
      { code: 180, label: 'Shrub/herbaceous, flooded',                color: '#00dc82', key: 'i', ndviRange: [0.2, 0.5],   seasonalPattern: 'Moderate, may spike with flooding' },
      { code: 190, label: 'Urban areas',                              color: '#c31400', key: 'o', ndviRange: [0.0, 0.1],   seasonalPattern: 'Stable, flat near zero' },
      { code: 200, label: 'Bare areas',                               color: '#fff5d7', key: 'p', ndviRange: [0.0, 0.1],   seasonalPattern: 'Stable, flat near zero' },
      { code: 210, label: 'Water bodies',                             color: '#0046c8', key: 'a', ndviRange: [-0.3, 0.0],  seasonalPattern: 'Stable, flat, negative values' },
      { code: 220, label: 'Permanent snow and ice',                   color: '#e8e8ff', key: 's', ndviRange: [-0.2, 0.1],  seasonalPattern: 'Stable, flat near zero' },
    ],
  },

  nlcd: {
    name: 'NLCD 2021 (16 classes)',
    description: 'US National Land Cover Database 2021 — 30m resolution, Continental US. Official MRLC colormap.',
    source: 'USGS NLCD 2021',
    url: 'https://www.mrlc.gov/data/nlcd-2021-land-cover-conus',
    classes: [
      { code: 11, label: 'Open Water',                       color: '#476ba0', key: '1', ndviRange: [-0.3, 0.0], seasonalPattern: 'Stable, flat, negative values' },
      { code: 12, label: 'Perennial Ice / Snow',             color: '#d1def8', key: '2', ndviRange: [-0.2, 0.1], seasonalPattern: 'Stable, flat near zero' },
      { code: 21, label: 'Developed, Open Space',            color: '#dec5c5', key: '3', ndviRange: [0.1, 0.4],  seasonalPattern: 'Mild seasonal green rise' },
      { code: 22, label: 'Developed, Low Intensity',         color: '#d99282', key: '4', ndviRange: [0.1, 0.3],  seasonalPattern: 'Low, slight summer green bump' },
      { code: 23, label: 'Developed, Medium Intensity',      color: '#eb0000', key: '5', ndviRange: [0.0, 0.2],  seasonalPattern: 'Low, slight summer green bump' },
      { code: 24, label: 'Developed, High Intensity',        color: '#ab0000', key: '6', ndviRange: [0.0, 0.1],  seasonalPattern: 'Stable, flat near zero' },
      { code: 31, label: 'Barren Land',                      color: '#b3ac9f', key: '7', ndviRange: [0.0, 0.1],  seasonalPattern: 'Stable, flat near zero' },
      { code: 41, label: 'Deciduous Forest',                 color: '#68ab5f', key: '8', ndviRange: [0.2, 0.9],  seasonalPattern: 'Drops in dormant season, recovers' },
      { code: 42, label: 'Evergreen Forest',                 color: '#1c5f2c', key: '9', ndviRange: [0.4, 0.8],  seasonalPattern: 'Consistently high, almost flat' },
      { code: 43, label: 'Mixed Forest',                     color: '#b5c58f', key: '0', ndviRange: [0.3, 0.9],  seasonalPattern: 'High with moderate seasonal dip' },
      { code: 52, label: 'Shrub / Scrub',                    color: '#ccb879', key: 'q', ndviRange: [0.2, 0.5],  seasonalPattern: 'Flat, minor seasonal variation' },
      { code: 71, label: 'Herbaceous',                       color: '#dfdfc2', key: 'w', ndviRange: [0.2, 0.6],  seasonalPattern: 'Gradual rise, one broad peak' },
      { code: 81, label: 'Hay / Pasture',                    color: '#dcd939', key: 'e', ndviRange: [0.3, 0.7],  seasonalPattern: 'Broad peak, possible cuts' },
      { code: 82, label: 'Cultivated Crops',                 color: '#ab6c28', key: 'r', ndviRange: [0.2, 0.8],  seasonalPattern: 'Sharp spike then sharp drop' },
      { code: 90, label: 'Woody Wetlands',                   color: '#b8d9eb', key: 't', ndviRange: [0.3, 0.8],  seasonalPattern: 'High, dips with flood pulse' },
      { code: 95, label: 'Emergent Herbaceous Wetlands',     color: '#6c9fb8', key: 'y', ndviRange: [0.2, 0.5],  seasonalPattern: 'Moderate, may spike with flooding' },
    ],
  },

  ipcc: {
    name: 'IPCC Land Use Categories (6 classes)',
    description: 'IPCC 2006 Guidelines for National Greenhouse Gas Inventories — 6 major land use categories for carbon accounting.',
    source: 'IPCC 2006 / 2019 Refinement',
    url: 'https://www.ipcc-nggip.iges.or.jp/public/2006gl/',
    classes: [
      { code: 1, label: 'Forest Land',   color: '#006400', key: '1', ndviRange: [0.3, 0.9],   seasonalPattern: 'High flat or seasonal dip' },
      { code: 2, label: 'Cropland',      color: '#ffff00', key: '2', ndviRange: [0.2, 0.6],   seasonalPattern: 'Sharp spike then sharp drop' },
      { code: 3, label: 'Grassland',     color: '#7fc97f', key: '3', ndviRange: [0.2, 0.6],   seasonalPattern: 'Gradual rise, one broad peak' },
      { code: 4, label: 'Wetlands',      color: '#4dbed2', key: '4', ndviRange: [0.2, 0.5],   seasonalPattern: 'Moderate, may spike with flooding' },
      { code: 5, label: 'Settlements',   color: '#ff0000', key: '5', ndviRange: [0.0, 0.1],   seasonalPattern: 'Stable, flat near zero' },
      { code: 6, label: 'Other Land',    color: '#888888', key: '6', ndviRange: [0.0, 0.1],   seasonalPattern: 'Stable, flat near zero' },
    ],
  },

  anderson_usgs: {
    name: 'Anderson / USGS Level I (9 classes)',
    description: 'USGS land-use and land-cover classification system for remote-sensor data (Anderson et al. 1976). Standard Level I.',
    source: 'USGS Professional Paper 964',
    url: 'https://pubs.usgs.gov/pp/0964/report.pdf',
    classes: [
      { code: 1, label: 'Urban or Built-up Land',    color: '#ff0000', key: '1', ndviRange: [0.0, 0.1],   seasonalPattern: 'Stable, flat near zero' },
      { code: 2, label: 'Agricultural Land',         color: '#ffff00', key: '2', ndviRange: [0.2, 0.6],   seasonalPattern: 'Sharp spike then sharp drop' },
      { code: 3, label: 'Rangeland',                 color: '#beae7d', key: '3', ndviRange: [0.2, 0.5],   seasonalPattern: 'Flat, minor seasonal variation' },
      { code: 4, label: 'Forest Land',               color: '#006400', key: '4', ndviRange: [0.3, 0.9],   seasonalPattern: 'High flat or seasonal dip' },
      { code: 5, label: 'Water',                     color: '#0000ff', key: '5', ndviRange: [-0.3, 0.0],  seasonalPattern: 'Stable, flat, negative values' },
      { code: 6, label: 'Wetland',                   color: '#4dbed2', key: '6', ndviRange: [0.2, 0.5],   seasonalPattern: 'Moderate, may spike with flooding' },
      { code: 7, label: 'Barren Land',               color: '#888888', key: '7', ndviRange: [0.0, 0.1],   seasonalPattern: 'Stable, flat near zero' },
      { code: 8, label: 'Tundra',                    color: '#b0c4de', key: '8', ndviRange: [0.1, 0.3],   seasonalPattern: 'Short summer green pulse' },
      { code: 9, label: 'Perennial Snow or Ice',     color: '#e8e8ff', key: '9', ndviRange: [-0.2, 0.1],  seasonalPattern: 'Stable, flat near zero' },
    ],
  },

  from_glc: {
    name: 'FROM-GLC (10 classes)',
    description: 'Finer Resolution Observation and Monitoring of Global Land Cover — Tsinghua University, 30m global map.',
    source: 'FROM-GLC v1 / Gong et al. 2019',
    url: 'http://data.ess.tsinghua.edu.cn/',
    classes: [
      { code: 1,  label: 'Cropland',           color: '#ffff00', key: '1', ndviRange: [0.2, 0.6],   seasonalPattern: 'Sharp spike then sharp drop' },
      { code: 2,  label: 'Forest',             color: '#006400', key: '2', ndviRange: [0.3, 0.9],   seasonalPattern: 'High flat or seasonal dip' },
      { code: 3,  label: 'Grassland',          color: '#7fc97f', key: '3', ndviRange: [0.2, 0.6],   seasonalPattern: 'Gradual rise, one broad peak' },
      { code: 4,  label: 'Shrubland',          color: '#9acd32', key: '4', ndviRange: [0.2, 0.5],   seasonalPattern: 'Flat, minor seasonal variation' },
      { code: 5,  label: 'Wetland',            color: '#4dbed2', key: '5', ndviRange: [0.2, 0.5],   seasonalPattern: 'Moderate, may spike with flooding' },
      { code: 6,  label: 'Water',              color: '#0000ff', key: '6', ndviRange: [-0.3, 0.0],  seasonalPattern: 'Stable, flat, negative values' },
      { code: 7,  label: 'Tundra',             color: '#b0c4de', key: '7', ndviRange: [0.1, 0.3],   seasonalPattern: 'Short summer green pulse' },
      { code: 8,  label: 'Impervious Surface', color: '#ff0000', key: '8', ndviRange: [0.0, 0.1],   seasonalPattern: 'Stable, flat near zero' },
      { code: 9,  label: 'Bareland',           color: '#888888', key: '9', ndviRange: [0.0, 0.1],   seasonalPattern: 'Stable, flat near zero' },
      { code: 10, label: 'Snow and Ice',       color: '#e8e8ff', key: '0', ndviRange: [-0.2, 0.1],  seasonalPattern: 'Stable, flat near zero' },
    ],
  },

  custom: {
    name: 'Custom (start blank)',
    description: 'Define your own classification schema from scratch.',
    source: 'Custom',
    classes: [],
  },
};

module.exports = PRESETS;
